### ISSUE TITLE
Sidebar Problems

### ISSUE THREAD

**Issue by ChrisGudd** [mywikis/HideSidebar#4]
Hello,
when I have installed this extension, the content of the sidebar is not displayed to me as an admin, despite the logged-in user.
I installed it as described at https://www.mediawiki.org/wiki/Extension:HideSidebar/de

Greetings & thanks for developing this extension <3

**Comment by jeffw16** [comment]
Could you send a screenshot? Please also let us know which version of this extension you are using and if you have added the `$wgEnableSidebarCache = false;` at the very end of your `LocalSettings.php`.

**Comment by ChrisGudd** [comment]
Extension Version: 2.1.1
MediaWiki Version: 1.38.2

$wgEnableSidebarCache = false; at the very end in LocalSettings.php is set.

![without-extension](https://user-images.githubusercontent.com/11297475/185609231-b41e0743-2af6-4c9c-bf2f-be9074dedf41.png)
![with-extension-logged-out](https://user-images.githubusercontent.com/11297475/185609252-29c5f706-cfb4-44fc-b0ea-10609fbd6458.png)
![withextension-logged-in](https://user-images.githubusercontent.com/11297475/185609263-3ec90c55-5622-4fb7-9b99-f4b0d08710f3.png)
![LocalSettings](https://user-images.githubusercontent.com/11297475/185609287-21ad325c-0416-4e53-aa5b-c572c0620288.png)
[LocalSettings.zip](https://github.com/mywikis/HideSidebar/files/9381773/LocalSettings.zip)

Greetings

**Comment by Seb35** [comment]
This issue occurs because User::isLoggedIn() is removed in MW 1.38. Usually there is an explicit message but given the mechanism [StubGlobalUser](https://github.com/wikimedia/mediawiki/blob/master/includes/StubObject/StubGlobalUser.php), it only fails explicitely the second time (see below).

The linked patch fixes this issue and removes the deprecated call to the global variable `$wgUser`.

```
$ php maintenance/eval.php
> var_dump( $wgUser->isLoggedIn() );
NULL
> var_dump( $wgUser->isLoggedIn() );
[b967eaf665e891bbb28d2d3e] [no req]   Error: Call to undefined method User::isLoggedIn()
```

**Comment by ChrisGudd** [comment]
Thanks for your response. Could you tell me where i have to paste the fixes?

**Comment by Seb35** [comment]
> Thanks for your response. Could you tell me where i have to paste the fixes?

The file to be modified is in `extensions/HideSidebar/HideSidebar.hooks.php` with [this modification](https://github.com/mywikis/HideSidebar/pull/5/files).

**Comment by ChrisGudd** [comment]
you're the King 🙌 

Everything works fine.

**Comment by jeffw16** [comment]
We have merged this change into our repo. Thank you very much @Seb35 for providing the patch and making the PR.
